import Head from 'next/head'
import Image from 'next/image'
import React, {useState, useEffect} from 'react'
import { useQuery, gql, useLazyQuery } from "@apollo/client"
import Card from '../components/Card';


const GET_PRODUCTS = gql`
  query{products(categoryId: "aeb50ed6-580d-a065-383a-e3932fbec6a1"){
    name
    price
    images{
      url
    }
  }}
`

export default function Home() {
  const [itemType, setItemType] = useState('Electronics')
  const {loading, data, error} = useQuery(GET_PRODUCTS)

  if (loading) { return <h1>Loading</h1> }
  if (error) { return <h1>error</h1> }

  return (
    <div className="overflow-y-clip  overscroll-none">
      <div className="sticky top-0 left0 bg-gray00 h-screen flex overflow-y-clip z-50 w-full bg-transparent-700 bg-gradient-to-l from-gray-100 to-transparent">
        <div className="free-space w-2/5 h-full"></div>
        <div className="right-side-bar w-3/5 bg-white z-60 h-full">
          <div className="header ">
            <div className="bg-red500 h-20 flex items-center justify-end">
              <div className="button mx-8 flex items-center border cursor-pointer border-gray-400 rounded-full px-2 py-1">
                <p>Close</p>
                <div className=" rounded-full mx-2 text-xs flex justify-center items-center p-2 px-2 h-3 w-3">
                  <p className="rounded-full flex justify-center items-center">3</p>
                </div>
              </div>
            </div>
          </div>
          <div className="bg-green- h-1 border-b border-white border-b-gray-300 mx-auto w-10/12"></div>
          <div className="sidebar-body h-full">

            <h1 className="m-16 mt-10 text-lg font-semibold">Order summary</h1>

            <div className="order-list">
              <div className="order h-44 border-b border-gray-500 flex justify-between items-center px-3 my-2">
                <img src="/Icons/profile.jpg" className="h-40 w-48 rounded-md" alt="" />
                <div className="bg-blue00 h-full w-full font-bold ml-2 mx-auto pl-10">
                  <div className="flex">
                    <div className="flex flex-col">
                    <h2>Wood Chair</h2>
                    <p className="font-light text-xs w-96 text-gray-900">Lorem ipsum dolor sit amet consectetur adipisicingo fugit natus cupiditate magnam quae nostrum deleniti provident consectetur inventore, libero beatae sunt at!</p>
                    </div>
                    <img src="/Icons/remove.svg" className="ml-10" alt="" />
                  </div>
                  <div className=" justify-between pr-10 h-20 bottom-0 w-10/12 -mb-10 flex items-end text-sm">
                    <p>$4,800.25</p>
                    <p className="flex justify-center items-center">
                      <img src="/Icons/add.svg" alt="" />
                      <p className="mx-4">2</p>
                      <img src="/Icons/minus.svg" alt="" />
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="nav w-full h-20 px-6 flex justify-between shadow-md">
        <div className="logo-section flex">
          <Image className="h-2 w-full" width="110" height="110" src="/Icons/logo.svg" />
        </div>
        <div className="nav-items flex">
          <ul className="flex justify-center items-center text-gray-400 font-bold text-sm">
            <li className="mx-8 cursor-pointer">Home</li>
            <span className="flex flex-col justify-center items-center">

              <li className="mx-8 cursor-pointer active mt-1 text-gray-800">Products</li>
              <span className="flex w-5 h-1 bg-gray-800 rounded-full"></span>
            </span>
            <li className="mx-8 cursor-pointer">Contact</li>
            <li className="mx-8 cursor-pointer">About</li>
          </ul>
        </div>
        <div className="profile-section flex items-center">
          <div className="bag flex flex-col justify-center items-center rounded-full p-2 border border-gray-300">
            <div className="num absolute rounded-full ml-3 bg-blue-500 -mr-5 text-xs px-1 -mt-5">3</div>
            <Image className="h-2 w-full" width="15" height="15" src="/Icons/bag.svg" />
          </div>
          <div className="profile mx-2 ml-5">
            <Image className="h-2 w-full rounded-full" width="32" height="32" src="/Icons/profile.jpg" />

          </div>
        </div>
      </div>


      {/* //////////////////////////////// */}
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="hero-section h-24 flex items-center justify-center">
          <div className="search-section">
            <form >
              <div className="search-wrapper w-auto bg-red500 border-2 border-gray-300 p-2 flex items-center justify-center rounded-full">
                <span className="search mx-3 flex justify-center items-center">

                  <Image className="h-2 mx-3 w-full" width="20" height="20" src="/Icons/search.svg" />
                </span>
                <input type="text" className="form-control w-96 h-6 focus:outline-none" placeholder="Search" />
              </div>
            </form>
          </div>
        </div>
        <div className="main-body h-auto bgrder-gray-400 b-red-600 w-full">
          <div className="nav mx-auto flex justify-center mb-6">
            <ul className="flex justify-evenly w-3/5 px-5 text-gray-400">
              <li className="cursor-pointer" onClick={() => setItemType('furniture')}>Furnitures</li>
              <li className="cursor-pointer" onClick={() => setItemType('electronics')}>Electronics</li>
              <li className="cursor-pointer" onClick={() => setItemType('vehicles')}>Vehicles</li>
              <li className="cursor-pointer" onClick={() => setItemType('accessories')}>Accessories</li>
              <li className="cursor-pointer" onClick={() => setItemType('fashion')}>Fashion</li>
            </ul>
          </div>
          <div className="main-container  border-t-2 g-red-600 h-full flex">
            <div className="filters w-2/6 g-blue-500">
              <div className="filter-text w-10/12 bg-re-600 border-b-2 mx-8 py-2">
                <h2>Filters</h2>
                {/* <span className="h-20 bg-gray-600 w-full"></span> */}
              </div>
              <div className="filters mx-auto pl-8">
                <ul className="text-sm font-semibol" styles={{ fontWeight: "550px" }}>
                  <li className="my-3">
                    <input type="checkbox" name="" className="bg-black" id="" /> <span className=" mx-2">Sofa</span>
                  </li>
                  <li className="my-3">
                    <input type="checkbox" name="" className="bg-black" id="" /> <span className=" mx-2">Beds</span>
                  </li>
                  <li className="my-3">
                    <input type="checkbox" name="" className="bg-black" id="" /> <span className=" mx-2">Tables</span>
                  </li>
                  <li className="my-3">
                    <input type="checkbox" name="" className="bg-black" id="" /> <span className=" mx-2">TV Stands</span>
                  </li>
                  <li className="my-3">
                    <input type="checkbox" name="" className="bg-black" id="" /> <span className=" mx-2">Wardrobs</span>
                  </li>
                  <li className="my-3">
                    <input type="checkbox" name="" className="bg-black" id="" /> <span className=" mx-2">Cabinates</span>
                  </li>
                  <li className="my-3">
                    <input type="checkbox" name="" className="bg-black" id="" /> <span className=" mx-2">Dressers</span>
                  </li>
                  <li className="my-3">
                    <input type="checkbox" name="" className="bg-black" id="" /> <span className=" mx-2">Other</span>
                  </li>
                </ul>
              </div>
            </div>
            <div className="display w-full bg-gren-600 bg-gray-50 flex flex-wrap">
              {data.products?.map((c) => {
                return (
                  <Card name={c.name} price={c.price} img={ c.images[0].url}/>
                )
              })}
            </div>
          </div>
        </div>
      </div>


      {/* /////////////////////////////// */}
      {/* <span className="absolute top-0 h-52">

      <div className="sticky top-0 left0 bg-red-500 h-screen w-full"></div>
      </span> */}
    </div>
  )
}
